# Video-Language Model Configuration

# Video Sampling
sample_fps: 1  # Video sampling FPS
clip_len: 4  # video clip len

# Query Embedding Match
topk: 8  # Top K matches for embedding
router_strategy: "cos_sim_fine"  # Router strategy: random, router, cos_sim_fine, cos_sim_coarse

# Memory Hyper Parameters
key_frame_buffer_size: 5  # Size of key frame buffer
key_frame_match_ratio: 0.5  # Match ratio for key frames
