# Video-Language Model Configuration

# Video Sampling
sample_fps: 1  # Video sampling FPS
clip_len: 4  # video clip len

# Query Embedding Match
topk: 8  # Top K matches for embedding
# Router strategy: random, router, cos_sim_fine, cos_sim_coarse, cross-attn
router_strategy: "cross-attn"

# Memory Hyper Parameters
key_frame_buffer_size: 3  # Size of key frame buffer
key_frame_match_ratio: 0.6  # Match ratio for key frames
max_frame_set_num: 5  # Maximum number of frames that can be merged into a single key frame
